site_name: Slyde
site_author: Tygo van den Hurk
site_url: https://tygo-van-den-hurk.github.io/Slyde/
site_description: Make beautifully animated Slydes and presentations from XML with ease!

repo_url: https://github.com/Tygo-van-den-Hurk/Slyde

theme: 
  name: shadcn
  icon: assets/logo-standalone.svg
  favicon: assets/logo-standalone.svg
  show_title: true
  show_stargazers: false
  pygments_style:
    light: github-light
    dark: github-dark
  highlightjs: false
  show_datetime: true
  color_mode: auto

plugins: 
  - search
  - mkdocstrings
  - callouts

markdown_extensions:
  - admonition
  - pymdownx.details
  - fenced_code
  - codehilite
  - attr_list
