name: Deploy to GitHub Pages
# Updates the GitHub pages website with the changes made in the last push.
# Takes in all markdown files and images of the repository and turns that
# into HTML to present on the GitHub pages website. Used for documentation.

on:
  workflow_dispatch:
  push:
    branches: [main, master, release, development]
    paths: [".github/workflows/push--deploy-github-pages.yaml", "mkdocs.yml", "docs/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:

  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with: { python-version: '3.x' }
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Cache pip
        uses: actions/cache@v5.0.1
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-
      - name: Install MkDocs and dependencies
        run: pip install --requirement 'docs/requirements.txt'
      - name: Build site with MkDocs
        run: mkdocs --verbose --color build --site-dir ./_site
      - name: Restore lychee cache
        uses: actions/cache@v5.0.1
        id: lychee-cache
        with:
          path: .lycheecache
          key: lychee-cache-docs-${{ hashFiles('docs/**/*.html', 'docs/**/*.htm') }}
          restore-keys: lychee-cache-docs-
      - name: Check the links
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            ./_site --verbose --max-concurrency 1
            --glob-ignore-case '**/*.{html,htm}'
            --hidden --no-progress --cache --max-cache-age 1d
      - name: Save lychee cache
        uses: actions/cache/save@v5.0.1
        with:
          path: .lycheecache
          key: ${{ steps.lychee-cache.outputs.cache-primary-key }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with: { path: ./_site }

  deploy:
    name: Deploy site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
