name: Deploy to GitHub Pages
# Updates the GitHub pages website with the changes made in the last push.
# Takes in all markdown files and images of the repository and turns that
# into HTML to present on the GitHub pages website. Used for documentation.

on:
  workflow_dispatch:
  push:
    branches: [main, master, release, development]
    paths: [".github/workflows/push--deploy-github-pages.yaml", "mkdocs.yml", "docs/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:

  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install MkDocs and dependencies
        run: >
          pip install mkdocs==1.6.1 mkdocs-shadcn==0.9.8 Pygments==2.19.2
          mkdocstrings-python==2.0.1 pymdown-extensions==10.19.1
          click==8.3.1 ghp-import==2.1.0 jinja2==3.1.6 markdown==3.10
          markupsafe==3.0.3 mergedeep==1.3.4 mkdocs-get-deps==0.2.0
          pathspec==0.12.1 pyyaml-env-tag==1.1 pyyaml==6.0.3 bottle==0.13.4
          watchdog==6.0.0 gitpython==3.1.45 mkdocstrings==1.0.0 griffe==1.15.0
          mkdocs-autorefs==1.4.3 python-dateutil==2.9.0.post0 gitdb==4.0.12
          smmap==5.0.2 colorama==0.4.6 platformdirs==4.5.1 six==1.17.0
      - name: Build site with MkDocs
        run: mkdocs --verbose --color build --site-dir ./_site
      - name: Restore lychee cache
        uses: actions/cache@v5.0.1
        id: restore-cache
        with:
          path: .lycheecache
          key: cache-docs-lychee-${{ github.sha }}
          restore-keys: cache-docs-lychee-
      - name: Check the links
        uses: lycheeverse/lychee-action@v2.6.1
        with:
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            ./_site --verbose --max-concurrency 1
            --glob-ignore-case '**/*.{html,htm}'
            --hidden --no-progress
      - name: Save lychee cache
        uses: actions/cache/save@v5.0.1
        with:
          path: .lycheecache
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with: { path: ./_site }

  deploy:
    name: Deploy site
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
